### ISSUE TITLE
Is this tool still supported?

### ISSUE THREAD

**Issue by tareksabry1337** [evandcoleman/Scipio#33]
I'm currently trying to integrate Scipio in my project so that I can cache my build on CI level but I keep running into errors like "Cannot initialize Kind from invalid String value remoteSourceControl" I even went ahead and forked it and did some arbitrary fixes so that everything works fine but even after fixing the enums I'm getting an infinite loop on "Reading Package.swift for swift-protobuf"

That's how my scipio.yml file looks like

```
name: [REDACTED]

deploymentTarget:
  iOS: "14.0"

cache:
  local:
    path: ./

packages:
  - name: Pushwoosh
    url: https://github.com/Pushwoosh/Pushwoosh-XCFramework
    from: 6.0.0
  - name: Firebase
    url: https://github.com/firebase/firebase-ios-sdk
    from: 9.0.0
  - name: Amplitude
    url: https://github.com/amplitude/Amplitude-iOS
    from: 8.0.0
  - name: Kingfisher
    url: https://github.com/onevcat/Kingfisher
    from: 7.0.0
  - name: CombineCocoa
    url: https://github.com/CombineCommunity/CombineCocoa
    from: 0.4.0
  - name: CombineExt
    url: https://github.com/CombineCommunity/CombineExt
    from: 1.0.0
  - name: Factory
    url: https://github.com/hmlongco/Factory
    from: 1.0.0
  - name: Lottie
    url: https://github.com/airbnb/lottie-ios.git
    from: 3.0.0
  - name: AutoChangeable
    url: https://github.com/almazrafi/AutoChangeable
    from: 1.0.0
  - name: ResponsiveTextField
    url: https://github.com/swensonhe/swift-responsive-textfield
    from: 0.0.0
  - name: Focuser
    url: https://github.com/swensonhe/swift-focuser
    from: 1.0.0
  - name: PhoneNumberKit
    url: https://github.com/marmelroy/PhoneNumberKit
    from: 3.0.0
  - name: ActivityIndicatorView
    url: https://github.com/exyte/ActivityIndicatorView
    from: 0.0.1
  - name: AWSiOSSDKV2
    url: https://github.com/aws-amplify/aws-sdk-ios-spm
    from: 2.0.0
```

And that's the output that it keeps looping

```
[18:07:34]: {
  "cLanguageStandard" : null,
  "cxxLanguageStandard" : null,
  "dependencies" : [

  ],
  "name" : "SwiftProtobuf",
  "packageKind" : {
    "root" : [
      "/Users/tareksabry/Library/Caches/Scipio/SourcePackages/[REDACTED]/checkouts/swift-protobuf"
    ]
  },
  "pkgConfig" : null,
  "platforms" : [

  ],
  "products" : [
    {
      "name" : "protoc-gen-swift",
      "settings" : [

      ],
      "targets" : [
        "protoc-gen-swift"
      ],
      "type" : {
        "executable" : null
      }
    },
    {
      "name" : "SwiftProtobuf",
      "settings" : [

      ],
      "targets" : [
        "SwiftProtobuf"
      ],
      "type" : {
        "library" : [
          "automatic"
        ]
      }
    },
    {
      "name" : "SwiftProtobufPluginLibrary",
      "settings" : [

      ],
      "targets" : [
        "SwiftProtobufPluginLibrary"
      ],
      "type" : {
        "library" : [
          "automatic"
        ]
      }
    },
    {
      "name" : "SwiftProtobufPlugin",
      "settings" : [

      ],
      "targets" : [
        "SwiftProtobufPlugin"
      ],
      "type" : {
        "plugin" : null
      }
    }
  ],
  "providers" : null,
  "swiftLanguageVersions" : [
    "4",
    "4.2",
    "5"
  ],
  "targets" : [
    {
      "dependencies" : [

      ],
      "exclude" : [

      ],
      "name" : "SwiftProtobuf",
      "resources" : [

      ],
      "settings" : [

      ],
      "type" : "regular"
    },
    {
      "dependencies" : [
        {
          "byName" : [
            "SwiftProtobuf",
            null
          ]
        }
      ],
      "exclude" : [

      ],
      "name" : "SwiftProtobufPluginLibrary",
      "resources" : [

      ],
      "settings" : [

      ],
      "type" : "regular"
    },
    {
      "dependencies" : [
        {
          "byName" : [
            "SwiftProtobufPluginLibrary",
            null
          ]
        },
        {
          "byName" : [
            "SwiftProtobuf",
            null
          ]
        }
      ],
      "exclude" : [

      ],
      "name" : "protoc-gen-swift",
      "resources" : [

      ],
      "settings" : [

      ],
      "type" : "executable"
    },
    {
      "dependencies" : [
        {
          "byName" : [
            "SwiftProtobuf",
            null
          ]
        }
      ],
      "exclude" : [

      ],
      "name" : "Conformance",
      "resources" : [

      ],
      "settings" : [

      ],
      "type" : "executable"
    },
    {
      "dependencies" : [
        {
          "byName" : [
            "protoc-gen-swift",
            null
          ]
        }
      ],
      "exclude" : [

      ],
      "name" : "SwiftProtobufPlugin",
      "pluginCapability" : {
        "buildTool" : null
      },
      "resources" : [

      ],
      "settings" : [

      ],
      "type" : "plugin"
    },
    {
      "dependencies" : [
        {
          "byName" : [
            "SwiftProtobuf",
            null
          ]
        }
      ],
      "exclude" : [

      ],
      "name" : "SwiftProtobufTests",
      "resources" : [

      ],
      "settings" : [

      ],
      "type" : "test"
    },
    {
      "dependencies" : [
        {
          "byName" : [
            "SwiftProtobufPluginLibrary",
            null
          ]
        }
      ],
      "exclude" : [

      ],
      "name" : "SwiftProtobufPluginLibraryTests",
      "resources" : [

      ],
      "settings" : [

      ],
      "type" : "test"
    }
  ],
  "toolsVersion" : {
    "_version" : "5.6.0"
  }
}

[18:07:34]: Reading Package.swift for swift-protobuf
[18:07:34]: /usr/bin/swift package dump-package --package-path /Users/tareksabry/Library/Caches/Scipio/SourcePackages/[REDACTED]/checkouts/swift-protobuf
[18:07:34]: warning: Usage of /Users/tareksabry/Library/org.swift.swiftpm/collections.json has been deprecated. Please delete it and use the new /Users/tareksabry/Library/org.swift.swiftpm/configuration/collections.json instead.
```
